---
- name: installing lamp
  hosts: webservers
  gather_facts: true
  become: true
  tasks:
  - name: Installing Apache, MYSQL & PHP
    yum:
      name:
        - apache2
        - mariadb-server
        - mariadb-devel
        - php
        - php-mysql
      state: installed
  - name: Enabling mysql service and start the service
    service:
      name: mariadb
      enabled: yes
      state: started
  - name: Enabling apache2 service and start the service
    service:
      name: apache2
      enabled: yes
      state: restarted
  - name: Copying php file in the /var/www/html
    copy:
      src: index.php
      dest: /var/www/html/index.php
      force: yes
...

