---
- name: installing lamp
  hosts: webservers
  gather_facts: true
  become: true
  tasks:
  - name: Installing Apache, MYSQL & PHP
    yum:
      name:
        - httpd
        - mariadb-server
        - mariadb-devel
        - php
        - php-mysql
      state: installed
  - name: Enabling mysql service and start the service
    service:
      name: mariadb
      enabled: yes
      state: started
  - name: Enabling httpd service and start the service
    service:
      name: httpd
      enabled: yes
      state: restarted
  - name: Copying php file in the /var/www/html
    copy:
      src: mahi.php
      dest: /var/www/html/mahi.php
      force: yes
    notify: Restart httpd
  handlers:
  - name: Restart httpd 
    service:
      name: httpd
      state: restarted
    
...

