---
- name: installing lamp
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
  - name: Installing Apache, MYSQL & PHP
    yum:
      name:
        - httpd
        - mariadb-server
        - mysqld
        - php
        - php-mysql
      state: installed
  - name: Enabling httpd service and start the service 
    service:
      name: httpd
      enabled: yes
      state: started
  - name: Enabling mysql service and start the service 
    service:
      name: mysqld
      enabled: yes
      state: started
  - name: Copying php file in the /var/www/html
    copy:
      src: /etc/ansible/index.php
      dest: /var/www/html/index.php
      force: yes
      
    notify: 
      - restarted httpd service 
  handlers:
  - name: restart the httpd service 
    service: 
      name: httpd
      state: restarted
...
