---
- name: ec2 launcher
  hosts: localhost
  connection: local
  become: true
  vars:
      instance_type: t2.micro
      key_pair: tomcat
      image_id: ami-0fa49cc9dc8d62c84
      vpc_subnet_id: subnet-090a90ba75ea92052
      region: us-east-2
      key: test
      value: test
  tasks:
    - name: launching ec2
      ec2:
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_pair }}"
        image: "{{ image_id }}"
        region: "{{ region }}"
        group: default
        count: 1
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        wait: yes
        assign_public_ip: yes
        state: "{{ state }}"
        instance_tags: {"key":"value"}
      register: assign_public_ip
    - name: Print the output of public_ip
      debug: var= assign_public_ip.stdout_lines
      
    - set_fact:
        public_ip={{ assign_public_ip.stdout_lines }}
    - debug: var=public_ip
  
...
